### ISSUE TITLE
Fcm message type

### ISSUE THREAD

**Issue by reshma-r-p** [saikatdutta1991/FirebaseCloudMessaging#1]
I have integrate it in my laravel application.  But the notification not working properly when it is is background. When i chceked i come to know that the notification type is, "Notification messages with optional data payload". 
_App behavior_ when receiving messages that include both notification and data payloads depends on whether the app is in the _background or the foreground_—essentially, whether or not it is active at the time of receipt.
- **When in the background**, apps receive the notification payload in the notification tray, and only handle the data payload when the user taps on the notification.
- **When in the foreground**, your app receives a message object with both payloads available.

So is there any way to use Data messages ?

**Comment by saikatdutta1991** [comment]
sorry for very late reply. I was developing this package for my learning purpose. 
	$fields = [
			"registration_ids" => $this->deviceTokens,
			"notification" => $this->buildNotification(),
			"priority" => $this->priority,
			'content_available' => $this->content_available,
	        'data' => $this->notifCustomPayload
	    ];

feel free to change the fields key properties as you want.. Basically i have observed that. when app is in background only "notification" property comes to notification tray and android shows the push notification. But when app is in foreground app receives both notification and data both payloads.. If you want, you can change directly in the file itself. Sorry once again.
