### ISSUE TITLE
What About multiple app under same firebase account ? 

### ISSUE THREAD

**Issue by azenmoktan** [saikatdutta1991/FirebaseCloudMessaging#3]
its not working for android and ios platform

**Comment by saikat-liftoffllc** [comment]
There must be some configuration you missed out on or If you can elaborate more about the errors that you are getting, I may help you.

**Comment by saikatdutta1991** [comment]
`What About multiple app under same firebase account ?` --> I didn't understand the question or it's not possbile using this lib. To be honest, this package was pretty immature. :)
